### ISSUE TITLE
Graph labels are sometimes cut off to the right

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1157]
Recently (on DC 5 codebase) we've observed that the job graph will have labels that are cut off to the right. Like this:

![image](https://cloud.githubusercontent.com/assets/291450/13072552/54696b58-d49a-11e5-813b-e821fa4accfb.png)

I don't have more information about the bug at the moment since no commonality has been established about when and why this happens.

**Comment by kaspersorensen** [comment]
Maybe a hunch worth considering: I tried deleting my DC home directory and then it stopped happening. I'm thinking that I may have had added some zooming/scaling of font sizes at some point in time and that the bug relates to that?

**Comment by LosD** [comment]
Seems plausible. I tried a single click on the font size + button, and the issue was gone.

Looking at the different font sizes, it seems to only be one click on - from (what I assume is) the standard size that has the issue. All other (usable) sizes seems to be okay. Maybe a simple workaround would be to just skip whatever that size translated to?

**Comment by arjansh** [comment]
@kaspersorensen, @LosD I can't reproduce this issue. can you both maybe look at it again and see if you can still reproduce it?

**Comment by LosD** [comment]
I can't reproduce anymore as well.

**Comment by LosD** [comment]
@ClaudiaPHI @jhorcicka has any of you seen it recently?

**Comment by jhorcicka** [comment]
Actually, I have never seen it.

**Comment by LosD** [comment]
Just talked with @ClaudiaPHI, she haven't seen it for a long time as well. Let's close it
