### ISSUE TITLE
Give up when trying to preview an input datastore with errors

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1191]
If a user tries to preview a datastore with errors, the preview will keep trying to read it, even if there is an error (i.e. wrong column count for a CSV row). This means that the preview dialog will keep putting up a blocking error dialog, which makes DC unusable until killed.

**Comment by kaspersorensen** [comment]
I did a bit of investigation on this issue and it's a bit of a difficult situation.

The `DataSetWindow` is created with a `TableModel` coming from MetaModel: `DataSet.toTableModel()`, which returns an instance of `DataSetTableModel`. That object is lazy-loaded so initially no issue is found when creating it. This means that the error actually happens when the JTable is rendering cells, not when it gets the model object. At that time we _can_ catch the exception, but the exception will be repeated again and again for every time Swing re-renders the table. So if I add just a simple logging statement, also that logging statement will be repeated again and again...

Seeing if I can find a neat way to avoid this. We should find this issue earlier IMO.
