### ISSUE TITLE
Generate ID transformer, offset is confusing for user, let's use "start with" instead

### ISSUE THREAD

**Issue by wvholland** [datacleaner/DataCleaner#1361]
I was really confused with this. Please fix it for me. :-)

**Comment by jhorcicka** [comment]
OK, I will start on this as soon as possible...

**Comment by wvholland** [comment]
We encountered this in the training. The transformer implicitly starts at 1. (which you don't know from scratch). (Keep reading !!!!)

The transformer is asking for an offset (default 0) and now the user needs to do its calculations. E.g. If I want to start at 100, then I need to set the offset on (100 - implicit 1) = 99. Bit of cumbersome. 
Could we change it a bit and instead of using offset, use 'starts with'

**Comment by LosD** [comment]
I disagree with the use of "starts with" instead of "offset". Offset is what we use everywhere else, and it's a very common word for this exact purpose. We might make it easier for the absolute beginner in any kind of data management, but at the cost of using a less precise and less used word.

I somewhat agree with the 99/100 discussion, though, but it is not really easy: There's always the danger that changing the behavior of the component may break existing jobs so they suddenly create duplicate row IDs. Imagine a job that always takes in 100 columns with IDs 1-100. The user want to add rows and sets the offset to 100 (again, the wording makes perfect sense here). After an upgrade with this fix, suddenly s/he would have duplicate IDs.

I'm maybe starting to think that the adding of one might make sense: holes in IDs are common (e.g. most deletions would introduce one) and usually harmless, duplicate IDs are usually pretty bad.

I really think we should add a description instead of changing it.

**Comment by LosD** [comment]
If we change it, it should at least be for a non-micro update since it changes behaviour, and we should document that it's a breaking change.

**Comment by wvholland** [comment]
In your example you assume that the user is aware of the fact that an offset of 100, implicitly means that the first next provided number is 101 (and not 100). I'm only suggesting that if we use another term (starts with - or even "next ID starts with" or whatever you like then all is more clear. We might also keep it like it is now and make it more clear in the documentation. With an example,

**Comment by LosD** [comment]
I'm not sure he would be acutely aware. I'm just assuming it would be natural to think "Oh, I have 100 records already, so it needs to be offset by 100". That, combined with "holes okay/duplicates bad" and the change of behavior makes me think it's the safe way.

I'll try to write up a good description

**Comment by LosD** [comment]
How about this:
> The row number offset. This is often used to insert into a database with existing sequential IDs. Since the transformer increments before inserting, an offset of e.g. 100 would make the first newly inserted ID 101.

**Comment by LosD** [comment]
Created a PR so we can discuss the actual solution. We can always close it if we decide to do something else instead (or we can do both if so decided).
