### ISSUE TITLE
Open job as template icw Oracle makes DC hang

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1372]
Originally submitted by @jacques-hi:

When a job is opened as a template you are offered to choose a different data store to map your job to.
If you select an Oracle datastore, DC will hang.

**Comment by jhorcicka** [comment]
Problem is actually not in Oracle (or any other) datastore itself. In this case the database contained a large amount of schemas each containing on average 100 tables (there was even one schema with 7000 tables in it). 

I propose to show a simple "progress dialog" with "Loading table 3/12 in schema 3/5...".

**Comment by jhorcicka** [comment]
![01](https://cloud.githubusercontent.com/assets/13213915/15748426/25a374fa-28df-11e6-8f49-569b375181d3.png)
![02](https://cloud.githubusercontent.com/assets/13213915/15748427/25c77792-28df-11e6-921d-e147a2196589.png)

**Comment by jhorcicka** [comment]
Because of various problems I left the idea with detailed text/description behind. Currently there is only "never-ending" progress bar. 

![01](https://cloud.githubusercontent.com/assets/13213915/17327367/c9dd6122-58b7-11e6-9547-23472b3df1d4.png)
![02](https://cloud.githubusercontent.com/assets/13213915/17327366/c9dc90c6-58b7-11e6-9e23-61c6c0a3f205.png)
![03](https://cloud.githubusercontent.com/assets/13213915/17327368/c9de1554-58b7-11e6-80a8-c5245e583517.png)

**Comment by ClaudiaPHI** [comment]
Maybe the progress bar should be on the window itself. The user might not understand to which window does it belong to. What is it loading ?! how does it behave when we minimize DC windows or we start other view ? Or if the user closes the dialog ?

**Comment by jhorcicka** [comment]
Useful comments, thanks @ClaudiaPHI. I replaced it with a LoadingIcon that is integrated into the dialog window. 

![loading-icon](https://cloud.githubusercontent.com/assets/13213915/17398982/01644b40-5a40-11e6-87ba-e89bd939db77.png)

**Comment by LosD** [comment]
Might want a little bit of air left and right of that icon. Looks pretty cramped.

**Comment by jhorcicka** [comment]
Right. 

![loading-icon](https://cloud.githubusercontent.com/assets/13213915/17399400/26e354c2-5a42-11e6-94a0-da45b5391010.png)

**Comment by LosD** [comment]
MUCH better :)
