### ISSUE TITLE
Component search based on keywords/alias - "Table lookup" not shown when inputting "join"

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1722]
I was demonstrating DC to a colleague this morning and a question came up: "How do I join two tables then?". I was forgetting that the name of the component is "Table lookup", so for a moment I was struggling to find it. In the component search/filter box I put in "join" but nothing showed up.

So I could formulate this issue / request two ways:

 * In particular: The "Table lookup" should somehow show up when searching for "join"
 * In general: Probably the filter should be expanded to look for aliases or keywords (I assume "join" is somewhere in the "Table lookup"s metadata.

**Comment by LosD** [comment]
This makes absolutely sense. Only thing is that I'd like it to then somehow show that it's the alias it reacted to, or otherwise make the aliases a little more visible. Otherwise searches could quickly become confusing.

Maybe something like this?
![image](https://cloud.githubusercontent.com/assets/1282832/25869752/c2935184-3501-11e7-9b5f-5d755aacf07c.png)

**Comment by kaspersorensen** [comment]
Sure, that would be icing on the cake I think :-) But if one was to build it without that UI improvement, would we accept the change? I might be intrigued to give it a shot :-)

**Comment by LosD** [comment]
I think so, but if it means search stops making sense, I'll reserve the right to reject (or maybe rather to add the labels myself) :)

But we don't have _THAT_ many components, so I don't think it'll be a real issue.
