### ISSUE TITLE
Matching and Standardization Function not available in 5.2

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1854]
Hello Community,

I'm evaluating DataCleaner on Windows version 5.2. Unfortunately, it doesn't appear to include the Matching and Standardization function. Is this because it's just not available in 5.2 or is it because the version I'm using is the Community edition?

Regards

**Comment by LosD** [comment]
Not entirely sure which function you are referring to? There's a few extra components available in the commercial edition, but AFAIK none of those go by that name (@arjansh , please correct me if I'm wrong).

I think we had component groups with names like that previously, though, but the groups has since been reshuffled and renamed. Or maaaaaybeee there's a group with that name in the commercial edition I've forgotten about.

You can see a full list of components in (the community edition of) 5.7.0 [here](https://datacleaner.github.io/docs/5.7.0/components/).

**Comment by cpatte7372** [comment]
Hi LosD,

Thanks for reaching out.

The Matching and Standarization was a function included elsewhere in the product. It is demonstrated in Datacleaner's YouTube video in 2015, you can see it here 
https://youtu.be/hZWxB_eu_A0

Anyway, it is included in the latest release, so please go ahead and close this case.

Regards
