### ISSUE TITLE
Schema tree is grayed out when building new job

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#208]
For some reason the schema tree started being grayed out when you build a new job. Note that this does NOT happen if you open a saved job.

![image](https://cloud.githubusercontent.com/assets/291450/5977474/ab98e75c-a898-11e4-9511-79d4b450dcd5.png)

**Comment by LosD** [comment]
This is.... Weird. The issue is _only_ present in a RC2 community build by @kaspersorensen, we can't reproduce at all with the same source, even when rebuilt with the community packaging.

We had a theory that it might be something about being run from the command line, or with the Java version, or run from a folder with space in the name, but we tried everything... Nothing 

We'll close this until we see it again.

**Comment by kaspersorensen** [comment]
I found an amazing hint to why this happens ... it ONLY happens when the datastore name is quite long. See here:

![image](https://cloud.githubusercontent.com/assets/291450/6124251/16cfcefc-b10c-11e4-875a-1345b6e043f9.png)

Note: This also happens on the 3.7.x versions, so not a new bug.

**Comment by kaspersorensen** [comment]
This has been fixed by not having the collapse/expand animation anymore.
