### ISSUE TITLE
Open job as a template will overwrite previous files

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#295]
If we have a job that contains writers to a CSV/Excel file with the option "Overwrite if exists" checked and we open the as a template pressing the "Execute" button means that we overwrite the data from previous job. Does the user wants that ?

**Comment by kaspersorensen** [comment]
This question is valid for any job or component that has side-effects such as writing to a file or database or changing anything else for that matter.

But I don't think it's possible to give any kind of generic answer. So my gut-feeling is to simply then stay in the logical modus which would argue that yes this is what is wanted since the job was designed this way and the user is choosing to load this particular job.

**Comment by kaspersorensen** [comment]
FYI - I don't think something like this is a bug (bugs are errors in the code that must be fixed), so I made a new label for it - "Type: Question" :)
