### ISSUE TITLE
"Create CSV file" to use a Resource instead of a java.util.File

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#494]
Instead of restricting ourselves to writing CSV _files_ we should rather change the "Create CSV file" analyzer to use a org.apache.metamodel.util.Resource instead of a java.util.File. That way we will enable also writing CSV content in other file systems than just local disk.

**Comment by ClaudiaPHI** [comment]
I have been working on this issue and I encountered the following problem while trying to write a HDFS Resource: 

Metamodel HDFSResource writes a file with default configuration which means that after the file is created, written and closed 3 replicas are automatically created and the file becomes immutable. Hadoop does not support append for files that have replicas. One can modify an existing file as long as it doesn't have additional replicas. 

Possible solutions: 

- Set in Metamodel HdfsResource, the Hdfs configuration the file to have 1 replica, which will allow appending. The downside of this, is that the user needs to manually create replicas on this file or we can create an option in DataCleaner for this situation after the user is done working with it. 

- Create a directory that contains partially files. Create a buffer of the size of a block in Hadoop (64M) and write a partial file.

**Comment by ClaudiaPHI** [comment]
Update on the solutions described in the previous message. 

Writing efficiently to HDSF is impossible at the moment. Metamodels CSV insertion builder is made to write to the file line by line. 
  
The CSV insertion builder uses the 2 methods: "write " respectively "append" on the Resource interface to create the file and respectively append each row. Practically for each row the file will be open and closed. 

HDFS files are  <b> write once - read multiple times </b> type of files, which means that the files once created and closed became immutable. Append is possible only if the number of replicas is set 1. practice which is considered dangerous if the file is very big. 
Hadoop creates a 64 MB block files and then proceeds to create the replicas for that block. 
In the current approach we create the replicas after the file has finished writing completely.  If the node crashes before the replicas are created the data is lost. 

Metamodels CSV insertion builder cannot have a buffer because there is no close method that could help us flush the buffer at the end of the file. Which means makes solution 2 extremely inefficient. Without the buffer the partial files will contain on line. 

At the moment I have implemented a workable solution 1).

There is need for a interface change to be able to implement solution 2.
