### ISSUE TITLE
DataCleaner removes the variables from the source definition in jobs

### ISSUE THREAD

**Issue by drexler42** [datacleaner/DataCleaner#512]
we have a job with a variable definition in the source section. This variable is used to determine the location of the output CSV file at runtime.

```
[... snip ...]
       </columns>
        <variables>
           <variable id="output_file_name" value="undefined"/>
        </variables>       
</source>
[... snip ...]
       <analyzer requires="outcome_0" name="ALL_OUT.csv">
 [... snip ...]
           <properties>
                <property name="File" ref="output_file_name"/>
```

When we open the file in DataCleaner 4.0.8 and then save it again (unmodified):
1. The variable definition dissappears completely
2. The reference to the variable is replaced by `value="some/path/in/.datacleaner"`

Desired functionality:
- Keep the variable definition and reference.

**Comment by kaspersorensen** [comment]
Hmm I am thinking how we could fix this issue... My concern is that we do not have any way to represent the "variable pointer" in the object model after it has been loaded from the XML format. I guess the proper solution to this problem would be to introduce that.

A hacked solution could be to add some metadata properties to the job that would be seen only by the XML reader and writer. But that sounds pretty dirty and if we eventually also want to add UI support for variables then it becomes even worse.

**Comment by kaspersorensen** [comment]
Thinking a bit more on this: I actually think the right thing to do would be to save the "variable information" in metadata properties. That way we keep the information but if a property value is requested then the concrete variable _value_ is returned, like it is today. Making some kind of variable value wrapper would be nice, but would break current API not to speak of introduce all kinds of data type issues in the code.

**Comment by tomaszguzialek** [comment]
@kaspersorensen, I would like to make sure I understand your idea correctly... 

In the XML file variables are kept in <source></source tags. The information is lost when JobType is transformed into AnalysisJobBuilder as it has _sourceColumns fields etc., but not a dedicated field for variables. Therefore, the variables should be saved in AnalysisJobBuilder in JobMetadata (maybe not the best place to keep it, but adding a dedicated field will break compatibility). When the AnalysisJob is saved back to XML file, it should be transferred back to <source></source> tag. 

We need to know during saving, which properties of which component were originally refering to the variable instead of just specifying a value directly. Therefore, during reading, we should save additional information in the component metadata itself - something like a map entry PROPERTY -> VARIABLE_ID.

Does that look good conceptually?

**Comment by kaspersorensen** [comment]
yes that's more or less the idea. I would propose to give a qualified prefix (such as 'datacleaner.jaxb.variable' or so) to that "temporary component metadata" so that we avoid any name clashes.
