### ISSUE TITLE
Spark job execution reports one more record than desktop execution

### ISSUE THREAD

**Issue by tomaszguzialek** [datacleaner/DataCleaner#598]
When the same DC job is run in desktop app and in the Spark cluster, the number of records reported by this job is off by one.

Most probably, Spark loads the whole file into RDD (including the header line) while desktop runner filters the header line out. Spark runner needs to take into account header line number from CsvConfiguration in input datastore and filter out this line from the RDD.

**Comment by kaspersorensen** [comment]
Found [1] this tip:  file.zipWithIndex().filter(_._2 > 0) 

[1] http://stackoverflow.com/questions/27854919/skipping-header-file-from-each-csv-file-in-spark

Actually to zip with index is good also for other things. It is kinda necesary for us to know the line number so that we can instantiate our InputRows with it. That gives us the same semantics of InputRow.getId() as in the normal DC (and that logic _is_ actually used a few places here and there).
