### ISSUE TITLE
Melon jobs UI Monkey testing

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#655]

**Comment by ClaudiaPHI** [comment]
Some findings while testing: 

Scenario: 

- The Datastore is the example Datastore Customers.csv 
- Added a Completeness Analyzer

**Comment by kaspersorensen** [comment]
I'm not sure I understand the sequence of things you did here. Which component did you remove?

**Comment by ClaudiaPHI** [comment]
"Convert to number"

**Comment by LosD** [comment]
Reproduced. Here's a step-by-step version.
1. Build new job.
2. Choose _Customers_ datastore.
3. Add _Completeness analyzer_.
4. Link _customers.csv_ to _Completeness analyzer_.
5. Add _Create Excel spreadsheet_.
6. Link "Complete rows" to _Create Excel spreadsheet_
7. Set sheet name to "test" in dialog (Why is this needed? Shouldn't there be a default?)
8. Add _String analyzer_.
9. Link "incomplete rows" to _String analyzer
10. Add _Convert to number_.
11. Double click _Convert to number_ and choose all rows.
12. Close

Expected behavior: Everything mapped correctly.

Actual behavior: One or more components may lose their mapping. I've seen zero loss, both lost their mapping and only _Create Excel spreadsheet_ lose it's mapping. At no point did I see _String analyzer_ lose its mapping, that may be because it was mapped last. All components seems to keep their scope setting.

Another issue I saw: The big help text only works for default scope. I had a moment of confusion when _Crate Excel spreadsheet_ had a stop-sign overlay, but the help text was all cheery.

**Comment by LosD** [comment]
By the way, shouldn't it have been created as a new issue instead of as a comment in here?

**Comment by ClaudiaPHI** [comment]
Do we create a separate issue for this  ? How do we handle it  ?

**Comment by LosD** [comment]
I would make a separate issue for all issues found (I can make one for the one I found with the cheery help text)

**Comment by ClaudiaPHI** [comment]
Created issue https://github.com/datacleaner/DataCleaner/issues/667
