### ISSUE TITLE
UI to setup credentials for remote components connection

### ISSUE THREAD

**Issue by jakubneubauer** [datacleaner/DataCleaner#718]
The Datacleaner Desktop user should be able to provide credentials for server providing remote components.

In previous discussions we agreed that for the future, the URL of the server will be in conf.xml with a default value pointing to a default cloud service providing non-standard components like address cleansing etc. So URL will be configurable only by expert users in conf.xml. But configuring login/password is a must-have for every user that wants to use the remote components.

We should think about the whole process: User registration, credit checking and charging, and configuring the credentials in the Desktop.
I think that good start will be a menu (called maybe like "Cloud extensions" or "Remote components" or ?)  having two items:
 - Register as a new user -> will open a web page in browser
 - Sign in with existing account -> Will open dialog to provide username/password. The server URL (taken from conf.xml) will be shown somewhere in a label, just informatively.

@kaspersorensen , please review...

**Comment by kaspersorensen** [comment]
I would add this as a new tab within the Options dialog.

In addition I think on the first startup we should prompt for username+password. Most users will just have registered online on datacleaner.org, so it should be the same credentials as the DC website. I imagine a simple prompt which briefly describes why you should log in, the two inputs (username and password) and then two buttons: "Log in" and "Not now".

**Comment by kaspersorensen** [comment]
Kinda important note from my side: I don't believe this will all be ready for the DC 4.5 release timeline. We don't have the time right now to put a central DC monitor in place, retrofit all the remote components and all that. So while I think it is a very good idea to develop this functionality, I don't want it on the master branch yet. If we post PRs, please make PRs for merging to a new "datacloud" branch instead of merging to master.
