### ISSUE TITLE
Use batching in remote transformers

### ISSUE THREAD

**Issue by jakubneubauer** [datacleaner/DataCleaner#726]
Extend RemoteTransformer from BatchTransformer. This allows to call remote service by batches of rows to overcome network latency.

**Comment by jakubneubauer** [comment]
Possible drawback: The actual network calls will be done in only one thread. Is it an issue for us?

**Comment by kaspersorensen** [comment]
Actually it is not blocking other threads so you will typically see 2-3 batches going on at the same time. The main bottleneck here will be the client's threadpool because it is still one-thread-per-record so if there are typically 10 records per batch call then it will be max 3 concurrent batch calls.

**Comment by kaspersorensen** [comment]
Given that the thread pool size is 30 (default setting)
