### ISSUE TITLE
CaptureChangedRecordsFilter loses the microseconds when a timestamp based column is used

### ISSUE THREAD

**Issue by ankit2711** [datacleaner/DataCleaner#806]
The CaptureChangedRecordsFilter loses the microseconds while reading back the long date value stored in the state file. This causes some jobs which use this filter for incremental runs to keep running through the same records. This becomes worse when the jobs are scheduled to run with a fixed time, even when no new records are added these scheduled jobs keep running through the same records again and again. 

We need to find a way that the date conversion from Long value (stored in the state file) does not loose on the microsecond value.

This is a blocker.

**Comment by kaspersorensen** [comment]
Do you not mean "just" nanoseconds? Or even millisecond precision? Because microsecond is _really_ tiny and to my knowledge not observable by most computers :-)
https://en.wikipedia.org/wiki/Microsecond

**Comment by kaspersorensen** [comment]
Been thinking a bit more about this and my suggestion would be to add one more long field in the filter to hold a fraction/higher precision comparison when two values are equal on the primary value.

In the saved resource we could then save this extra number only when it is not zero. I would suggest to save it with a separator after the primary number. Like 10000042.6538 would mean that 6538 is the fraction (nano sin case of timestamp comparison).

This approach would mean that compatibility is retained because the precision or scale is not changed for the primary number, we only add one more number.
