### ISSUE TITLE
Hidden columns should be shown in property widget(s) if selected

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#970]
Scenario

1. Start a job with Orderdb, add Customer table to canvas 
2. select "Convert to String" Transformer 
3. Select at least 2 input columns. 
4. Deselect (hide) one of the output columns in the "Output columns" task pane.
5. Write Data to csv with default selected columns. 
6. Run the job. 

Expected output: 
The file should have only the selected columns in the CSV transformer. 

Actual output: 

 The file contains the deselected output column.

**Comment by ClaudiaPHI** [comment]
Can someone give me a hint. Which property widget should I look into ?

**Comment by LosD** [comment]
I think it's in ColumnListTable/MutableInutColumnListPanel

**Comment by kaspersorensen** [comment]
MultipleInputColumnsPropertyWidget

**Comment by kaspersorensen** [comment]
Coming back to what this is about ...

We DONT want to disable hiding of columns - it's a feature that is useful in many scenarios. It's simply that it's a feature which has a bug: The hiding should only be active on a particular column list (MultipleInputColumnsPropertyWidget) if the column is not in use/selected.

**Comment by ClaudiaPHI** [comment]
When you hide a column, doesn't that mean you deselect the column ? The actual problem is that the column remains selected even if it is not shown in the column list of other analyzer/transformer.

**Comment by kaspersorensen** [comment]
No that would be a too strong side-effect that it suddenly deselects something from another component.

**Comment by ClaudiaPHI** [comment]
Then what is the point of hiding it the column ? It's strange. What I understand by deselecting that column is that I have no further use for it.

**Comment by kaspersorensen** [comment]
It will no longer appear in the column lists where it is not already selected (which will anyways be the case mostly because a user would not want to hide a column that he knows he is using).

**Comment by ClaudiaPHI** [comment]
Ok. But that it is not intuitive. I expect to see all the columns I am using,because I will not remember them otherwise. In my view, If I hide a column it means that I do not need it, and I do not want to have too many columns available in my next component.

In that case the issue it is not a bug.

**Comment by kaspersorensen** [comment]
It is a bug, but you're focusing on the wrong use case IMO.

Imagine you do Name cleansing on a given name and last name. The name cleansing component outputs a lot of fields like prefix, initials, gender, postfix, honorific, full name. But you just want to update your 2 columns: given name and family name. So you choose to hide all the other ones.

Now when you then double click the Update table component to configure it you don't want to see prefix, initials, gender, postfix, honorific and full name. This is the hiding feature.

BUT if you had already previously made an Update table component which used maybe the gender field, THEN it should still be visible because it is used/selected. This is the change that we want: If the column is used/selected then it shouldn't be hidden.

**Comment by ClaudiaPHI** [comment]
To add something to this story: 

 * We should make sure "link to" wiring is also sensitive about hidden columns (don't wire them)
 * We should make sure the transformer's "write data" button also does not wire hidden columns.
